---
name: Release

on:
  push:
    tags:
      - "v*.*.*.*"

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      SCRIPT_NAME: wasd_instead_of_arrows.ahk
      RELEASE_FILE_NAME: wasd_instead_of_arrows_${{ github.ref_name }}.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set version in ahk file
        shell: pwsh
        run: |
          $version="${{ github.ref_name }}"
          (Get-Content ${{ env.SCRIPT_NAME }}) -replace 'VERSION_PLACEHOLDER', $version |
            Set-Content ${{ env.SCRIPT_NAME }}

      - name: Build exe
        uses: MohamedSaidSallam/AHK2Exe-GitHub-Action@v1
        with:
          in: ${{ env.SCRIPT_NAME }}
          out: ${{ env.RELEASE_FILE_NAME }}
          icon: icon.ico

      - name: Calculate SHA256
        id: hash
        shell: pwsh
        run: |
          $hash = Get-FileHash -Path "${{ env.RELEASE_FILE_NAME }}" -Algorithm SHA256
          echo "hash=$($hash.Hash)" >> $env:GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          body: |
            SHA256: ${{ steps.hash.outputs.hash }}
          files: ${{ env.RELEASE_FILE_NAME }}

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          url: ${{ steps.release.outputs.url }}
          description: |
            New Version (`${{ github.ref_name }}`).
            [Check out the it out!](${{ steps.release.outputs.url }})
